### ISSUE TITLE
Pretrained weight

### ISSUE THREAD

**Issue by slf007** [Soroorsh/deep-disaster#1]
Dear Sir:
               Thanks for your work, When I run the model ,it said No such file or directory: 'pre_trained/imagenet_netG_last_new.pth'.
               could you tell me how to get the weights.   Thank you very much

**Comment by Soroorsh** [comment]
Hi, 
you can download the pre-trained weights from [here](https://drive.google.com/drive/folders/1GrDqzoLKQMdUSduH2lwGc8EOAecX3GXt?usp=sharing)
I am not a sir, I am a girl :))
